Add tests / add toggle view functionality / fix some alignment issues
KKoukiou/cockpit-navigator pull request #25
Opened 2023-05-16 13:24 UTC by KKoukiou

2023-05-16 13:52 UTC, MahmoudHamdy02 submitted a review, later dismissed

2023-05-16 14:05 UTC, MahmoudHamdy02 submitted a review, later dismissed

2023-05-16 14:07 UTC, martinpitt requested changes
Thanks! Nice to see some first real tests!

2023-05-16 14:07 UTC, martinpitt commented on test/check-application
> +        m.execute("rmdir /home/admin/newdir && rm /home/admin/newfile")
Please don't use `&&`. m.execute() is already running under `set -e`, and the semantics of `&&` are really weird.

2023-05-17 07:17 UTC, martinpitt approved these changes
Thanks!

Double click is weird, we don't use that anywhere else in Cockpit nor is it a common thing in the browser. I'd suggest to redesign this. But that's unrelated to this PR.

2023-05-17 07:17 UTC, merged