Add arrow button navigation
KKoukiou/cockpit-navigator pull request #9
Opened 2023-05-14 08:43 UTC by MahmoudHamdy02

2023-05-15 09:10 UTC, KKoukiou requested changes
I have some concern regarding the implemetation of this .
SO you consider 0 index the /home/oneuser directory right? This is slightly confusing because you want to be able to reach also / so that would give you negative indexes for these directories. 

SO I believe it would be better implemeted if using full paths only for the state, not the indexes.

Also when performing the navigation the breadcrumb should also change.

Lastly the back button should be disabled when there is nowhere back to go to (being at /)


I am not sure what the forward button is meant for in the mockups, I need to recheck this.

2023-05-15 11:54 UTC, MahmoudHamdy02 commented
I've adjusted most of the points except for starting the navigator in the user home directory, since it kept giving me infinite loops and memory leaks :/
I'll look into it again when the `cockpit.channel` is added

2023-05-15 14:24 UTC, KKoukiou requested changes

2023-05-15 14:24 UTC, KKoukiou commented on src/app.jsx
> +                    <Flex>
It's easy to fix the spacing,
`<Flex spaceItems={{ default: "spaceItemsXs" }}>` will decrease it.

2023-05-15 19:57 UTC, MahmoudHamdy02 commented
Added the requested changes

2023-05-16 07:33 UTC, KKoukiou approved these changes

2023-05-16 07:33 UTC, merged